logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
server:
  servlet:
    context-path: /flight-reservation
